### ISSUE TITLE
PubSubClient library required: which one?

### ISSUE THREAD

**Issue by zoomx** [sapienzaapps/seismoclouddevice-arduino#1]
Compiling for Arduino UNO platform require a PubSubClient library.
I used this one
[https://github.com/knolleary/pubsubclient](url)
but I get these errors

```
sketch/api.cpp:118: undefined reference to `PubSubClient::connect(char const*, char const*, char const*, char const*, unsigned char, bool, char const*)'

sketch/api.cpp:155: undefined reference to `PubSubClient::state()'

sketch/api.cpp:160: undefined reference to `PubSubClient::subscribe(char const*, unsigned char)'

C:\Users\zoomx\AppData\Local\Temp\ccv1AVXg.ltrans1.ltrans.o: In function `apiTick()':

sketch/api.cpp:168: undefined reference to `PubSubClient::loop()'

C:\Users\zoomx\AppData\Local\Temp\ccv1AVXg.ltrans1.ltrans.o: In function `apiDisconnect()':

sketch/api.cpp:97: undefined reference to `PubSubClient::publish(char const*, unsigned char const*, unsigned int, bool)'

sketch/api.cpp:98: undefined reference to `PubSubClient::disconnect()'
```
so I wander if I used a different library or made some errors

**Comment by Enrico204** [comment]
Hi @zoomx , the library you're using is the right one. I'm using Arduino IDE 1.8.1 and PubSubClient 2.6 (the latest stable AFAIK).

It seems that the linker cannot find the right library. Which version of PubSubClient are you using?

Thanks :-)
Enrico

**Comment by zoomx** [comment]
Enrico,
I used the last commit on github, not the release. Anyway I made a mistake because instead of installing the library in the library folder I installed in the sketch folder and changed the path in common.h
Sometimes it works but in this source it doesn't work.

So I put the library in library folder and get other errors
```
Arduino: 1.8.2 (Windows 7), Board: "Arduino/Genuino Uno"

Archiving built core (caching) in: C:\Users\zoomx\AppData\Local\Temp\arduino_cache_845441\core\core_arduino_avr_uno_534dac807388a814d249a9d0e3164952.a
C:\Users\zoomx\AppData\Local\Temp\cc3CAGti.ltrans0.ltrans.o: In function `update':

sketch/update.cpp:29: undefined reference to `pf_mount'

sketch/update.cpp:61: undefined reference to `pf_open'

sketch/update.cpp:79: undefined reference to `pf_lseek'

sketch/update.cpp:99: undefined reference to `pf_write'

sketch/update.cpp:121: undefined reference to `pf_write'

sketch/update.cpp:138: undefined reference to `pf_write'

collect2.exe: error: ld returned 1 exit status

exit status 1
Error compiling for board Arduino/Genuino Uno.

```
but this is a different error, I believe, so if you want I can open another issue and close this one.

**Comment by Enrico204** [comment]
Hi @zoomx , I'm sorry that you have these issues!

please see if your setup is aligned with https://github.com/sapienzaapps/seismoclouddevice-arduino/blob/master/Arduino.md#how-to-build-arduino-code ; to sum up:

 - Copy PetitFS to Arduino/libraries/ (in your home folder, as other libraries)
 - modify/fix EthernetClient class (in Arduino_IDE_folder/libraries/Ethernet/src/EthernetClient.cpp) as specified into the manual linked above

unfortunately I had no time to update docs. I'll check the website and the repo ASAP.

I'm closing this issue, if you still have problem with PetitFS and/or you did the step above and didn't work, please open a new issue ;-)

Thanks for supporting this project :-)
